apiVersion: v1
kind: Service
metadata:
  name: string-reverse
  namespace: default
  labels: 
    app: string-reverse
spec:
  selector:
    app: string-reverse
  sessionAffinity: None
  ports:
  - port: 8090    
  type: ClusterIP