apiVersion: v1
kind: Service
metadata:
  name: random-num-reverse-str
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  ran-num-rev-str-svc_mapping
      prefix: /reverse/
      rewrite: /api/string/reverse/
      service: random-num-reverse-str
  labels: 
    app: random-num-reverse-str
spec:
  selector:
    app: random-num-reverse-str
  sessionAffinity: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
